require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*
    - bench/**/*

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 7

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - str_metrics.gemspec

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 120

Naming/MethodParameterName:
  AllowedNames:
    - a
    - b

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
